feat(todo-13): call api to add a task
syed-alif-sazim/todo-list-app pull request #10
Opened 2024-12-17 13:49 UTC by syed-alif-sazim

**Description of change**
Call an API route to add a task

**Associated trello link**
https://trello.com/c/6R5vUWRE

2024-12-20 08:56 UTC, mahir-mohsin-sazim requested changes

2024-12-20 08:56 UTC, mahir-mohsin-sazim commented on .env
> +NEXT_PUBLIC_BE_URL=http://localhost:3005
Why your secrets are part of your commit? Please check you `gitignore` file.

2024-12-21 15:16 UTC, nur-zaman-sazim approved these changes

2024-12-22 15:05 UTC, mahir-mohsin-sazim approved these changes

2024-12-25 12:30 UTC, merged