feat(todo-16): call api to toggle completion
syed-alif-sazim/todo-list-app pull request #13
Opened 2024-12-17 13:58 UTC by syed-alif-sazim

**Description of change**
Call an API route to change the completion status of a task

**Associated trello link**
https://trello.com/c/BmL8RSg7

2024-12-18 14:50 UTC, nur-zaman-sazim commented on modules/todo/containers/TodoPage/TodoPage.tsx
> +      console.log(tasks)
let's remove the console log

2024-12-20 09:04 UTC, mahir-mohsin-sazim requested changes

2024-12-20 09:04 UTC, mahir-mohsin-sazim commented on modules/todo/containers/TodoPage/TodoPage.helpers.ts
> +    const response = await axios.put(`${API_URL}/tasks/${task.id}`, { description: task.description });
handle the payload the way you are doing it for the `addTask` functionality

2024-12-20 09:04 UTC, mahir-mohsin-sazim commented on modules/todo/containers/TodoPage/TodoPage.tsx
> +                <TaskList tasks={tasks} onDelete={(id) => handleDeleteTask(id, setTasks)}  onEdit={(task) => handleEditTask(task, setTasks)} onToggleComplete={(taskId) => handleToggleComplete(taskId,
Can you suggest a better way instead of passing the functions as props in `TaskList` component. If there is then why did not you follow that approach?

2024-12-22 15:15 UTC, mahir-mohsin-sazim requested changes

2024-12-22 15:15 UTC, mahir-mohsin-sazim commented on modules/todo/containers/TodoPage/TodoPage.helpers.ts
> +export const handleDeleteTask = async (id: number, dispatch: React.Dispatch<any>) => {
avoid using `any`

2024-12-24 16:04 UTC, mahir-mohsin-sazim requested changes
can you please double check this PR? I can still see couple of `any` types.

2024-12-25 10:33 UTC, mahir-mohsin-sazim approved these changes

2024-12-25 12:18 UTC, merged