feat(todo-12) : Display all tasks in a list
syed-alif-sazim/todo-list-app pull request #3
Opened 2024-12-05 20:34 UTC by syed-alif-sazim

**Description of change**
-All tasks created by users will be fetched from localstorage and rendered in the frontend
-completed tasks will appear striked

**Associated trello links**
https://trello.com/c/7pIXLow6

**Screenshot of change**
![image](https://github.com/user-attachments/assets/71ad49de-08e6-46db-b5d6-2536fb4c75a3)

2024-12-06 05:57 UTC, mahir-mohsin-sazim commented
For future PRs, Please follow appropriate commit messages. Follow Github Conventional Commit. And for PR descriptions follow [this](https://docs.google.com/document/d/1mNcOLYRSEUsc9dvmw4V_0xgCAhvjd5PXup6KqdFsT-E/edit?tab=t.0#heading=h.trqjxpk8qcdo)

2024-12-06 06:31 UTC, mahir-mohsin-sazim requested changes

2024-12-06 06:31 UTC, mahir-mohsin-sazim commented on modules/todo/containers/TodoPage/TodoPage.tsx
> +        <div className="w-full max-w-md bg-white p-6 rounded-lg shadow-md mt-8">
NIT: look into tailwind css directives.

2024-12-06 06:31 UTC, mahir-mohsin-sazim commented on modules/todo/utils/localStorage.ts
> +export const saveTasksToLocalStorage = (tasks: any[]) => {
Please avoid using any type

2024-12-07 00:11 UTC, syed-alif-sazim commented on modules/todo/containers/TodoPage/TodoPage.tsx
> +        <div className="w-full max-w-md bg-white p-6 rounded-lg shadow-md mt-8">
Bhai where is it? I did not find it in the engineering principles doc.

2024-12-07 13:22 UTC, mahir-mohsin-sazim commented on modules/todo/containers/TodoPage/TodoPage.tsx
> +        <div className="w-full max-w-md bg-white p-6 rounded-lg shadow-md mt-8">
Its not in our doc. Its in [Tailwind documentation](https://tailwindcss.com/docs/functions-and-directives)

2024-12-07 13:24 UTC, mahir-mohsin-sazim approved these changes

2024-12-07 17:10 UTC, merged