Todo: Polish frontend
syed-alif-sazim/todo-list-app pull request #8
Opened 2024-12-11 13:35 UTC by syed-alif-sazim

**Description of change**
-Multiple spaces between words renders in UI
-Big words wrap properly 
-If a task's description is too big, its truncated version appears along with the option of viewing the entire description in a scrollable modal
-No space between add task text field and button
-No edit button when a task has completed status
-Zod validation and error display for adding and editing tasks

**Screenshots of change**
![image](https://github.com/user-attachments/assets/5c210f80-f06b-43d3-9c04-c34ac378bbfb)
![image](https://github.com/user-attachments/assets/386d993b-0804-4bc3-bae2-4ec7ba9864de)
![image](https://github.com/user-attachments/assets/f796b2ce-8f29-4267-8da4-222b7cb0e5ef)
![image](https://github.com/user-attachments/assets/b8e8d0c0-07b5-4f79-9166-df5bf4959e6f)
![image](https://github.com/user-attachments/assets/4aaa3a72-3801-48b6-b388-fc6810d53685)
![image](https://github.com/user-attachments/assets/3e917103-c5e8-46f2-935d-df1cb8727771)

2024-12-11 19:37 UTC, nur-zaman-sazim requested changes

2024-12-11 19:37 UTC, nur-zaman-sazim commented on modules/todo/components/TaskItem/TaskItem.tsx
> +
This can be moved to helper.ts file

2024-12-11 19:37 UTC, nur-zaman-sazim commented on modules/todo/components/TaskItem/TaskItem.tsx
> +            <div className="mt-2 text-red-500 text-sm">{error}</div> // Display validation errors
please remove comments

2024-12-11 19:37 UTC, nur-zaman-sazim commented on modules/todo/components/TaskItem/TaskItem.tsx
> +          }}
why are we using raw css here ? Let's use tailwind classes.

2024-12-11 23:19 UTC, ishmamur-rahman-sazim requested changes

2024-12-11 23:19 UTC, ishmamur-rahman-sazim commented on modules/todo/components/TaskItem/TaskItem.tsx
> +          {truncateDescription(task.description, 100)}
Since `maxLength` is a fixed number, let's create a shared `constants.ts` file and define `MAX_DESCRIPTION_LENGTH` there. This would make it reusable, and remove the need for the second param in `truncateDescription` definition.
[Read up on magic values](https://kyleshevlin.com/what-are-magic-values/)

2024-12-11 23:21 UTC, ishmamur-rahman-sazim commented
Please update the PR title to make sure it's following conventions.

2024-12-12 07:57 UTC, mahir-mohsin-sazim requested changes

2024-12-12 07:57 UTC, mahir-mohsin-sazim commented on modules/todo/containers/TodoPage/TodoPage.tsx
>      const [tasks, setTasks] = useState<{ id: number; description: string; isCompleted: boolean }[]>([]);
Why not use a `Type` or `Interface` instead of `{ id: number; description: string; isCompleted: boolean }` to keep the code clean

2024-12-12 07:57 UTC, mahir-mohsin-sazim commented on modules/todo/components/TaskItem/TaskItem.tsx
> +                style={{
Raw CSS ?

2024-12-12 07:57 UTC, mahir-mohsin-sazim commented on modules/todo/components/TaskInput/TaskInput.helpers.ts
> +export const TaskSchema = z.string().min(1, { message: "Description cannot be empty" });
NITPICK: Honestly, its title, not description

2024-12-12 07:58 UTC, mahir-mohsin-sazim commented
Its not ideal to repeat myself, but I will do it again. Fix your commit messages.

2024-12-13 10:12 UTC, mahir-mohsin-sazim approved these changes

2024-12-13 10:22 UTC, merged